name: Deploy to GCP VM

on:
  push:
    branches:
      - main  # your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/nati-nicolae/find-my-seat  #  the root from the VM where you clone the repo
          git pull origin main
          cd frontend
          npm install
          npm run build
